#!/usr/bin/env bash
#This script displays the username, user ID, and home directory from /etc/passwd.
exec < /etc/passwd

while IFS= read -r line
do
    username=$(echo "$line" | cut -d: -f1)
    user_id=$(echo "$line" | cut -d: -f3)
    home_directory=$(echo "$line" | cut -d: -f6)

    echo "Username: $username"
    echo "User ID: $user_id"
    echo "Home Directory: $home_directory"
    echo
done
