#!/usr/bin/env bash
#This script displays formatted information based on the /etc/passwd file.
IFS=':' 
while read -r username password group_id full_name home_directory shell
do
    echo "The user $username is part of the $group_id gang, lives in $home_directory and rides $shell."
    echo "USER ID's place is protected by the passcode $password, more info about the user here: $full_name"
    echo
done < /etc/passwd
