#!/usr/bin/env bash
#This script displays formatted information based on the /etc/passwd file.
IFS=':' 

while read -r username password user_id group_id full_name home_directory shell
do
    echo "The user $username is part of the $group_id gang, lives in $username and rides $home_directory:$shell."
    echo "USER ID's place is protected by the passcode $password, more info about the user here: $user_id"
    echo
done < /etc/passwd
