#!/usr/bin/env bash
#this script displays time from 0:1 to 12:59 showing only the first 70 lines
hour=0

while [ $hour -le 12 ]
do
    minute=1
    while [ $minute -le 59 ]
    do
        echo "$hour:$minute"
        minute=$((minute + 1))
    done
    hour=$((hour + 1))
done | head -n 70

