#!/usr/bin/env bash
#This script lists the files in the current directory, showing only the part after the first dash.
for file in *  
do
    if [[ "$file" == *-* ]]  
    then
        echo "${file#*-}"  
    else
        echo "$file"  
    fi
done
