#!/usr/bin/env bash
# shellcheck disable=SC2009
for pid in /proc/[0-9]*; do
    cmd=$(cat "$pid/cmdline" 2>/dev/null | tr '\0' ' ')
    if [[ $cmd == *bash* ]]; then
        echo "$(basename "$pid") $cmd"
    fi
done
